#!/bin/bash

set -ex

# jupyter labextension install @jupyter-widgets/jupyterlab-manager qgrid

# ls *ipynb | xargs -0 perl -i -p -e 's/^   "name": ".*"$/   "name": "conda-env-notebook-py"/g'

python kernel_replacer.py

/bin/rm -f README.md environment.yml kernel_replacer.py postBuild

echo "
import sxs

sxs.write_config(download=True, cache=True)
sxs.load('catalog')
sxs.load('SXS:BBH:0123/Lev/metadata.json')
sxs.load('SXS:BBH:0123/Lev/Horizons.h5')
sxs.load('SXS:BBH:0123/Lev/rhOverM')
sxs.load('SXS:BBH:0314/Lev/metadata.json')
sxs.load('SXS:BBH:0314/Lev/Horizons.h5')
sxs.load('SXS:BBH:0314/Lev/rhOverM.*')
" | python


