#!/bin/bash

set -ex

python -m pip install --upgrade --no-deps sxs
python -m pip install jupyterlab_widgets ipywidgets

python kernel_replacer.py

echo "
import sxs

sxs.write_config(download=True, cache=True)
sxs.load('simulations')
sxs.load('SXS:BBH:0123')
sxs.load('SXS:BBH:0123').horizons
sxs.load('SXS:BBH:0123').h
sxs.load('SXS:BBH:0123', auto_supersede=True).h
sxs.load('SXS:BBH:1234')
sxs.load('SXS:BBH:1234').horizons
sxs.load('SXS:BBH:1234').h
sxs.load('SXS:BBH:1124')
sxs.load('SXS:BBH:1124').horizons
sxs.load('SXS:BBH:1124').h
sxs.load('SXS:BBH:0314/Lev/metadata.json')
sxs.load('SXS:BBH:0314/Lev/Horizons.h5')
sxs.load('SXS:BBH:0314/Lev/rhOverM.*')
" | python

/bin/rm -f README.md environment.yml kernel_replacer.py postBuild
